# version: '3.9'

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend_new
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    # environment:
    #   - NODE_ENV=development  # 개발 환경 설정
    #   # - NEXT_PUBLIC_API_URL=/api/v1/  # 상대 경로로 변경
    #   - NEXT_PUBLIC_API_URL=http://backend:8080/api/v1 #이게 가장 처음 되던거
      # - NEXT_PUBLIC_API_URL=http://localhost:6666/api/v1
    restart: always
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend_new
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    environment:
        - NODE_ENV=development
        - PORT=8080  # 포트 환경변수 추가
        - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
    depends_on:
      db:
        condition: service_healthy
    restart: always  # on-failure 대신 always 사용
    networks:
      - app-network
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s  # 컨테이너 시작 후 헬스체크 시작까지 대기 시간

networks:
  app-network:
    driver: bridge
volumes:
  pgdata: {}
