FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# 빌드 시 환경변수 설정
ENV NODE_ENV=development
ENV NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1

EXPOSE 3000

# 개발 서버 실행
CMD ["npm", "run", "dev"]